// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtiIehdCJpvp1Jlk81BmX7P6Hbr5N4Xb0',
    appId: '1:757965643418:web:0c7a2a9450470fd5904923',
    messagingSenderId: '757965643418',
    projectId: 'bms-data-84467',
    authDomain: 'bms-data-84467.firebaseapp.com',
    databaseURL: 'https://bms-data-84467-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bms-data-84467.firebasestorage.app',
    measurementId: 'G-S3B7P1ZMPP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcU7VMy5zSVnqAWiY6PdVUd11XO2YNCm4',
    appId: '1:757965643418:android:8af2b4783b2bb707904923',
    messagingSenderId: '757965643418',
    projectId: 'bms-data-84467',
    databaseURL: 'https://bms-data-84467-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bms-data-84467.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBM-Gts0cQr5jBH9uQ34yO8hlFrPVCm5qQ',
    appId: '1:757965643418:ios:4a3250654922068f904923',
    messagingSenderId: '757965643418',
    projectId: 'bms-data-84467',
    databaseURL: 'https://bms-data-84467-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bms-data-84467.firebasestorage.app',
    iosBundleId: 'com.example.newBmsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBM-Gts0cQr5jBH9uQ34yO8hlFrPVCm5qQ',
    appId: '1:757965643418:ios:4a3250654922068f904923',
    messagingSenderId: '757965643418',
    projectId: 'bms-data-84467',
    databaseURL: 'https://bms-data-84467-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bms-data-84467.firebasestorage.app',
    iosBundleId: 'com.example.newBmsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDtiIehdCJpvp1Jlk81BmX7P6Hbr5N4Xb0',
    appId: '1:757965643418:web:fa23b7164079a11c904923',
    messagingSenderId: '757965643418',
    projectId: 'bms-data-84467',
    authDomain: 'bms-data-84467.firebaseapp.com',
    databaseURL: 'https://bms-data-84467-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bms-data-84467.firebasestorage.app',
    measurementId: 'G-GL70NVPY4F',
  );
}
